### ISSUE TITLE
documentation needed

### ISSUE THREAD

**Issue by mohofo7** [RingsNetwork/rings-node#408]
Hi,
Thanks for this interesting project

I searched in this repo and organization for any documentation about how to use or Bootstrap example but I didn't found and I stuck on how to use this.
there is another project called rings-fe, but I think that project needs to be updated to the latest version. Furthermore cant run a success message on that project (sorry for mention here).

so could you please provide any guidance about how to use it?

**Comment by mohofo7** [comment]
for more information,

when I want to connect a peer from Chrome to Firefox, I got this error:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/39581812/235199479-9de4e120-8bb6-4efa-9749-b60455783a6b.png">

(rings-fe project)

**Comment by RyanKung** [comment]
Thank you for your response and for taking an interest in our project. We are currently in the process of documenting our work, and we plan to release the `rings-fe` demo soon. 

The error shown in the screenshot may result in a lack of successor nodes when attempting to run a stabilization operation.
