### ISSUE TITLE
Convergent implementation of WASM and NATIVE

### ISSUE THREAD

**Issue by RyanKung** [RingsNetwork/rings-node#453]
### Motivation

In order to ensure a convergent implementation between WebAssembly (Wasm) and the native version, two principles should be followed:

1. More shared code: Both implementations should strive to have a larger portion of the codebase in common. This means implementing common functionalities, structures, and algorithms in a way that is shared between the two versions.

2. Minimizing differences: Any differences between the Wasm and native implementations should be kept to a minimum. This involves carefully identifying and isolating the areas where divergence is necessary due to technological constraints or platform-specific requirements.

### Proposed Solution

* The Processor/Client should use the same Config/ConfigBuilder: This means that both the Processor and Client components should utilize a shared Config or ConfigBuilder object for consistent configuration across the system. This helps maintain uniformity and ensures that both components have access to the same configuration settings.

* Utilize the same method invocation approach, such as RPC: It is important to adopt a unified approach for invoking methods between different components. Using a consistent method invocation mechanism, such as Remote Procedure Calls (RPC), ensures that the Processor and Client can communicate and interact seamlessly, regardless of their underlying technologies or implementation details.

* Use the same Logging module and Error handling module: Employing a common Logging module and Error handling module ensures consistency in logging practices and error management across the system. By utilizing the same logging framework and error handling mechanism, it becomes easier to track and troubleshoot issues, promoting code maintainability and efficient debugging.

### Alternatives

A clear and concise description of any alternative solutions or features you've considered, and why you're proposed solution is better.

**Comment by r2d2-rs** [comment]
This issue is moved to https://github.com/RingsNetwork/rings-node/discussions/492
