### ISSUE TITLE
RFC3: Data & RelayMessage storage

### ISSUE THREAD

**Issue by RyanKung** [RingsNetwork/rings-node#87]
Algorithm:

* Resource ID

RID is a DID (Distributed ID) without public key, and `rid(data) = sha1(data).hex()`
MID is a DID (Distributed ID) without public key, and `rid(relay_target) = BigUint(relay_target) + 1`
   - A MID will always store at the closest node of target or itself.

* Set/Get Data

Given a peer A

```
fn dht_set(rid<data>) {
    match peer_a.find_successor(rid) {
          Some(peer_a) => peer_a.local_store(data),
          RemoteAction::FindSuccessor(b, rid) => {
               // tell remote node B to store rid.
          }
    }
}
```
           

```
fn dht_get(rid<data>) {
    match peer_a.find_successor(rid) {
          Some(peer_a) => peer_a.local_fetch(data),
          RemoteAction::FindSuccessor(b, rid) => {
               // tell remote node B to fetch rid.
          }
    }
}
```

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/662346/164220951-b2c19ff8-8e54-4565-8a5d-187565b19250.png">

* Stabilize on update successor

```
If self.successor is updated:
      for did in peer.local_storage():
            if did in [self, new_successor]:
                   new_successor.storage(rid)
```

**Comment by Ma233** [comment]
Rid should be `rid(key) = sha1(key).hex()`
The set function should be like: `fn dht_set(rid<key>, data)`

**Comment by RyanKung** [comment]
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/662346/164204691-c7ec5472-d64d-406e-bff6-f3359a377403.png">
The  synchronous mechanism of K/V in origin paper is trigged while a node join Ring and ask `find_successor`, then copy range of k/v from its successor to self.

Our implementation is to pegging the stable-notify process, when a Node find it's new predecessor, it should send data to it.

**Comment by RyanKung** [comment]
Close because outdated
